### ISSUE TITLE
Propose eslint rules for import order

### ISSUE THREAD

**Issue by ssncferreira** [relayr/eslint-config-relayr#6]
Import order: https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md
This one seems very configurable. The way I usually do is by grouping imports based on the following:
```
// require third party libraries
const uuid = require('uuid/v4')

// require relayr specific libraries
const RelayrLog = require('cloud-nodelib-log')

// require local files
const utils = require('../utils')
```

**Comment by yuvke** [comment]
I think this is super useful to reading through imports quickly. Two notes

1. It seems that there's no easy way to discern between `third party` and `relayr specific` libs. We could try to define a custom group with a pattern like `"cloud-*"` (everything that starts with *cloud-*). The rule supports this configuration but I'm not sure how bulletproof this is. Maybe a better option would be to just treat the relayr ones as external ones as well (or change them to start with `@realyr/`).
2. I would add the system node ones as a first group like so:
``` javascript
// require node libraries
const uuid = require('fs')

// require third party libraries
const uuid = require('uuid/v4')

// require relayr specific libraries
const RelayrLog = require('cloud-nodelib-log')

// require local files
const utils = require('../utils')
```

**Comment by bernardpletikosa** [comment]
if we can have a rule that separates relayr specific stuff by 'cloud-' prefix that's already enough. let's not change anything with libs because of linting.

**Comment by WaleedAshraf** [comment]
I'm good with approach @yuvke suggested. And use "cloud-" for relayr ones.
All new rules should start as "warn" level, and after some time turned to "error" level.

@relayr/nodejs My recommendation would be, when you start working a service/package, first, please update eslint-config to latest version and create a PR (from master to master) with "auto fix" all eslint issues.

Than create your development PR (from master to master) and don't fix any linting issue in it.
