### ISSUE TITLE
Propose eslint rule for JSDoc

### ISSUE THREAD

**Issue by ssncferreira** [relayr/eslint-config-relayr#7]
JSDoc: https://eslint.org/docs/rules/valid-jsdoc

This one is something that we already agreed before, but never actually documented. Is to in the JSDoc `param` arguments always use lower case for primitive types (e.g., `string`, `number`, etc), and upper case for non-primitive types (e.g., `Object`, `Array`).
Other configurations are also possible.

```
/**
 * @param {Array<Object>} messages
 * @param {string} eventType
 * @returns {Object}
 */
```

**Comment by bernardpletikosa** [comment]
So what do we do when we agree with something?
Who creates the PR with the update?

**Comment by WaleedAshraf** [comment]
You mean PR in eslint-config to add the rules?
I can do that...that's the easy part.
@bernardpletikosa

**Comment by ssncferreira** [comment]
> So what do we do when we agree with something?
> Who creates the PR with the update?

Sorry I hadn't had the time to create the PR for these issues. So, @WaleedAshraf can you do it for this one?

**Comment by 19shubham11** [comment]
Also, we should agree on how to document an Arrays of numbers or strings. Right now, we have the following in our codebase at different places
- `Array<string>`
- `String`
- `Array`

I think `Array<string>`  is the way to go here as well

**Comment by 19shubham11** [comment]
Plus, upon looking at JsDoc, it seems like the convention is `Array.<type>`. 
See these 
- https://jsdoc.app/tags-type.html
- https://stackoverflow.com/questions/14611995/how-to-specify-an-array-of-objects-as-a-parameter-or-return-value-in-jsdoc

**Comment by WaleedAshraf** [comment]
@19shubham11 I think both are fine.
Maybe we shouldn't enforce them? As long as it's there, it's ok.

If you see here, JSDoc is using `Object[]` https://jsdoc.app/tags-param.html

Also, this is taken from link you shared.
https://jsdoc.app/tags-param.html
![image](https://user-images.githubusercontent.com/8335457/85309918-99c21300-b4b3-11ea-918d-b35034539dbe.png)

So, there are two valid ways, both means the same.

```
Array.<Object>
Object[]
```

@ssncferreira

**Comment by 19shubham11** [comment]
hmm yeah 🤔 but shouldn't we be picking one of these to be consistent?

**Comment by WaleedAshraf** [comment]
For now, I'd say it's okay to have both. Atleast it's there :p
Later we can switch to one. Otherwise it'll be too many changes now.

**Comment by Richard-Boyewa** [comment]
Since we are planning on setting a standard, there is no point confusing ourselves having more than one. Lets choose one and stick to it. IMO. Personally, I prefer this `Array.<Object>`, because this `Object[]` can also depict a collection (key-value collection).

**Comment by WaleedAshraf** [comment]
I couldn't find a way to enforce that.

Can you create a new issue and a PR do discuss and then add it?

cc @Richard-Boyewa @19shubham11

**Comment by ssncferreira** [comment]
I agree with @Richard-Boyewa if we are adding a set of rules for JSDoc it makes sense to define already the ones that we want to use and be consistent. Since we agreed to keep these rules violations as a warning for now there is no need to change all at once. Of course some rules will still be missing, but this is an iterative process and we can add them later on.
