### ISSUE TITLE
Propose new eslint rule for line breaks in object declaration

### ISSUE THREAD

**Issue by ssncferreira** [relayr/eslint-config-relayr#9]
Line breaks in object declaration / destructuring: https://eslint.org/docs/rules/object-curly-newline

This one I don't have a clear opinion. It was proposed by @yuvke so maybe he can add further details about the best configuration for this one 🙂

**Comment by yuvke** [comment]
I think this is something I noticed that people take liberty on how to write and use different approaches. My view is that uniformity is always better in the long run when working across a large code base. Specifically I would recommend the following configuration:
```
{
    "object-curly-newline": ["error", { "minProperties": 3 }]
}
```
``` javascript
// Up to two properties you don't have to break into a new line
let a = {};
let b = {foo: 1};
let c = {foo: 1, bar: 2};

// From three properties and above you must break into a new line
let d = {
    foo: 1,
    bar: 2,
    baz: 3,
};

// This also applies to destructering
let {foo, bar} = obj;
let {
   foo,
   bar,
   baz,
} = obj;
``

**Comment by bernardpletikosa** [comment]
> I think this is something I noticed that people take liberty on how to write and use different approaches. My view is that uniformity is always better in the long run when working across a large code base. Specifically I would recommend the following configuration:
> 
> ```
> {
>     "object-curly-newline": ["error", { "minProperties": 3 }]
> }
> ```

I like the proposed config.
If it would break of anything with 1 or 2 props it would be too annoying imho.

**Comment by WaleedAshraf** [comment]
Good with @yuvke suggestion. Let's add this as "warn" level.

**Comment by ssncferreira** [comment]
@yuvke I like the suggestion 🚀 Can you create a PR for this one?

**Comment by 19shubham11** [comment]
`error` would just break some stuff when we introduce this 🤷 
(but that will have to be fixed as a separate PR with the new lib version then )

**Comment by ssncferreira** [comment]
@yuvke yes. All new rules should be with `warn` level for now 🙂

**Comment by bernardpletikosa** [comment]
@WaleedAshraf @yuvke @Richard-Boyewa any idea what happened with this?
